-- migrations/20251020_create_full_hris_schema.up.sql

-- ============================================================
-- 1. USER MANAGEMENT (RBAC CUSTOM)
-- ============================================================

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE, 
    is_active BOOLEAN NOT NULL DEFAULT TRUE, 
    last_login TIMESTAMPTZ,                   
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL, 
    display_name VARCHAR(100) NOT NULL 
);

CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255) 
);

CREATE TABLE "Provinces" (
  "ProvinceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "ItemId" VARCHAR(20) UNIQUE, 
  "ProvinceName" VARCHAR(100)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- ============================================================
-- 2. HRIS CORE TABLES (Dikonversi dari T-SQL ke PostgreSQL)
--    Semua tabel dari dump Anda, dihubungkan melalui Foreign Keys.
-- ============================================================

CREATE TABLE "TimeZones" (
  "TimeZoneId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TimeZoneName" VARCHAR(100) NOT NULL,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Holidays" (
  "HolidayId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "HolidayName" VARCHAR(255),
  "HolidayDate" TIMESTAMPTZ,
  "HolidayDescription" VARCHAR(500),
  "IsNationalHoliday" BOOLEAN,
  "IsCompanyHoliday" BOOLEAN,
  "IsSpecialHoliday" BOOLEAN,
  "CreatedDate" TIMESTAMPTZ,
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ,
  "UpdatedBy" VARCHAR(100),
  "HolidayYear" INT,
  "IsMassLeave" BOOLEAN NOT NULL
);

CREATE TABLE "AttendanceLocations" (
    "AttendanceLocationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TimeZoneId" INT NULL,
    "LocationName" VARCHAR(255) NULL,
    "IsFlexible" BOOLEAN NULL,
    "Latitude" NUMERIC(11, 8) NULL,
    "Longitude" NUMERIC(11, 8) NULL,
    "RadiusToleranceInMeter" INT NULL,
    "CreatedDate" TIMESTAMPTZ NULL,
    "CreatedBy" VARCHAR(100) NULL,
    "UpdatedDate" TIMESTAMPTZ NULL,
    "UpdatedBy" VARCHAR(100) NULL
);

CREATE TABLE "Company" (
  "CompId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CompName" VARCHAR(150),
  "CompAddress" VARCHAR(500),
  "CompZipCode" VARCHAR(10),
  "CompPhoneNumber" VARCHAR(20),
  "CompMobileNumber" VARCHAR(25),
  "CompEmail" VARCHAR(50),
  "CompWebsite" VARCHAR(300),
  "CompRetirementAge" INT,
  "PersentasePendapatanBPJSTKPemberiKerja" FLOAT,
  "PersentasePendapatanBPJSKSPemberiKerja" FLOAT,
  "PersentasePenguranganBPJSTKPemberiKerja" FLOAT,
  "PersentasePenguranganBPJSKSPemberiKerja" FLOAT,
  "PersentasePenguranganBPJSTKPekerja" FLOAT,
  "PersentasePenguranganBPJSKSPekerja" FLOAT,
  "CompanyPrevMonthDayPayroll" INT NOT NULL DEFAULT 21,
  "CompanyCurrentMonthDayPayroll" INT NOT NULL DEFAULT 20,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Branches" (
  "BranchId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CompId" INT REFERENCES "Company" ("CompId"),
  "TimeZoneId" INT REFERENCES "TimeZones" ("TimeZoneId"),
  "BranchName" VARCHAR(100) NOT NULL,
  "CompanyName" VARCHAR(255) NOT NULL,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Organizations" (
  "OrganizationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrganizationName" VARCHAR(200) NOT NULL,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "JobLevels" (
  "JobLevelId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "JobLevelName" VARCHAR(100) NOT NULL,
  "JobLevelOrder" INT,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "JobPositions" (
  "JobPositionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "JobPositionName" VARCHAR(100),
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "EmploymentStatus" (
  "EmploymentStatusId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EmploymentStatusName" VARCHAR(100) NOT NULL,
  "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "CreatedBy" VARCHAR(100),
  "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
  "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Classes" (
  "ClassId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassCode" VARCHAR(50)
);

CREATE TABLE "Grades" (
  "GradeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "GradeCode" VARCHAR(50) NOT NULL
);

CREATE TABLE "PtkpTypes" (
  "PtkpTypeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PtkpCode" VARCHAR(20)
);

CREATE TABLE "OvertimeSettings" (
  "OvertimeSettingId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OvertimeName" VARCHAR(200)
);

CREATE TABLE "ZipCodes" (
  "ZipCodeId" VARCHAR(10) PRIMARY KEY,
  "District" VARCHAR(50) NOT NULL,
  "County" VARCHAR(50) NOT NULL,
  "City" VARCHAR(50) NOT NULL
);

CREATE TABLE "Shifts" (
  "ShiftId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShiftCode" VARCHAR(50),
  "ShiftName" VARCHAR(100)
  -- Kolom tambahan lainnya dari T-SQL diabaikan untuk fokus relasi
);

CREATE TABLE "TimeOffPolicies" (
  "TimeOffPolicyId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TimeOffPolicyCode" VARCHAR(20) NOT NULL,
  "TimeOffPolicyName" VARCHAR(255) NOT NULL
);

CREATE TABLE "AttendanceTypes" (
  "AttendanceTypeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AttendanceTypeCode" VARCHAR(20)
);

-- CREATE TABLE StandardReferences (Master List)
CREATE TABLE "StandardReferences" (
    "StandardReferenceId" VARCHAR(100) PRIMARY KEY,
    "StandardReferenceName" VARCHAR(255) NOT NULL,
    "IsActive" BOOLEAN,
    "Note" VARCHAR(255),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

-- CREATE TABLE StandardReferenceItems (Items/Details)
CREATE TABLE "StandardReferenceItems" (
    "StandardReferenceId" VARCHAR(100) REFERENCES "StandardReferences" ("StandardReferenceId"),
    "ItemId" VARCHAR(100) NOT NULL,
    "ItemName" VARCHAR(255),
    "IsActive" BOOLEAN,
    "Note" VARCHAR(255),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100),
    PRIMARY KEY ("StandardReferenceId", "ItemId")
);

-- ============================================================
-- 3. EMPLOYEES (BRIDGING HRIS TO RBAC)
-- ============================================================

CREATE TABLE "Employees" (
  "EmployeeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BranchId" INT REFERENCES "Branches" ("BranchId"),
  "OrganizationId" INT REFERENCES "Organizations" ("OrganizationId"),
  "JobLevelId" INT REFERENCES "JobLevels" ("JobLevelId"),
  "JobPositionId" INT REFERENCES "JobPositions" ("JobPositionId"),
  "EmploymentStatusId" INT REFERENCES "EmploymentStatus" ("EmploymentStatusId"),
  "ManagerId" INT, -- Self-reference: REFERENCES "Employees" ("EmployeeId")
  "ClassId" INT REFERENCES "Classes" ("ClassId"),
  "UserId" BIGINT REFERENCES users ("id"), -- FK KE USERS CUSTOM
  "GradeId" INT REFERENCES "Grades" ("GradeId"),
  "EmployeeNumber" VARCHAR(20) NOT NULL,
  "Email" VARCHAR(54),
  "BirthDate" TIMESTAMP WITHOUT TIME ZONE,
  "IsActive" BOOLEAN,
  "GajiPokok" FLOAT
);

ALTER TABLE "Employees" ADD FOREIGN KEY ("ManagerId") REFERENCES "Employees" ("EmployeeId");

-- ============================================================
-- 4. RELASI TRANSAKSI DAN LOG KE EMPLOYEES
-- ============================================================

CREATE TABLE "AttendanceLogs" (
    "AttendanceLogId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AttendanceTypeId" INT NULL,
    "ShiftId" INT NULL,
    "TimeZoneId" INT NULL,
    "AttendanceLocationId" INT NULL,
    "EmployeeId" INT NULL,
    "AttendanceLogDate" TIMESTAMPTZ NULL,
    "Clock" VARCHAR(10) NOT NULL,
    "Latitude" NUMERIC(11, 8) NULL,
    "Longitude" NUMERIC(11, 8) NULL,
    "SelfiePath" VARCHAR(255) NULL,
    "ClockViaType" VARCHAR(100) NULL,
    "InOut" VARCHAR(1) NULL,
    "CreatedDate" TIMESTAMPTZ NULL,
    "CreatedBy" VARCHAR(100) NULL,
    "UpdatedDate" TIMESTAMPTZ NULL,
    "UpdatedBy" VARCHAR(100) NULL,
    "LateIn" VARCHAR(10) NULL,
    "EarlyOut" VARCHAR(10) NULL,
    "Note" VARCHAR(1000) NULL,
    "ActionDate" TIMESTAMPTZ NULL
);

CREATE TABLE "Attendances" (
    "AttendanceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShiftId" INT NULL,
    "TimeZoneId" INT NULL,
    "AttendanceTypeId" INT NULL,
    "EmployeeId" INT NULL,
    "AttendanceLocationId" INT NULL,
    "AttendanceDate" TIMESTAMPTZ NOT NULL,
    "ClockIn" VARCHAR(10) NULL,
    "ClockOut" VARCHAR(10) NULL,
    "LateIn" VARCHAR(10) NULL,
    "EarlyOut" VARCHAR(10) NULL,
    "LatitudeIn" NUMERIC(11, 8) NULL,
    "LongitudeIn" NUMERIC(11, 8) NULL,
    "LatitudeOut" NUMERIC(11, 8) NULL,
    "LongitudeOut" NUMERIC(11, 8) NULL,
    "SelfieInPath" VARCHAR(255) NULL,
    "SelfieOutPath" VARCHAR(255) NULL,
    "ClockInViaType" VARCHAR(100) NULL,
    "ClockOutViaType" VARCHAR(100) NULL,
    "AttendanceCode" VARCHAR(20) NULL,
    "TimeOffPolicyCode" VARCHAR(20) NULL,
    "ScheduleWorkingHour" VARCHAR(10) NULL,
    "ActualWorkingHour" VARCHAR(10) NULL,
    "RealWorkingHour" VARCHAR(10) NULL,
    "CreatedDate" TIMESTAMPTZ NULL,
    "CreatedBy" VARCHAR(100) NULL,
    "UpdatedDate" TIMESTAMPTZ NULL,
    "UpdatedBy" VARCHAR(100) NULL,
    "IsClockOutOverlapDay" BOOLEAN NULL,
    "ClockInNote" VARCHAR(1000) NULL,
    "ClockOutNote" VARCHAR(1000) NULL,
    "TimeOffPolicyId" INT NULL,
    "ActionDateClockIn" TIMESTAMPTZ NULL,
    "ActionDateClockOut" TIMESTAMPTZ NULL
);

-- Tabel yang mereferensi EmployeeId (Daftar singkat)
CREATE TABLE "Archives" ( "ArchiveId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "Category" VARCHAR(50) );
CREATE TABLE "EmergencyContacts" ( "EmergencyContactId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "ContactName" VARCHAR(150) );
CREATE TABLE "FormalEducations" ( "FormalEducationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "EducationLevelType" VARCHAR(100) );
CREATE TABLE "InformalEducations" ( "InformalEducationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "EducationName" VARCHAR(255) );
CREATE TABLE "Families" ( "FamilyId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "FamilyName" VARCHAR(150) );
CREATE TABLE "EmployeeFiles" ( "EmployeeFileId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "Category" VARCHAR(50) );
CREATE TABLE "TimeOffs" ( "TimeOffId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "TimeOffPolicyId" INT REFERENCES "TimeOffPolicies" ("TimeOffPolicyId"), "StartDate" TIMESTAMP WITHOUT TIME ZONE );
CREATE TABLE "WorkExperiences" ( "WorkExperienceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EmployeeId" INT REFERENCES "Employees" ("EmployeeId"), "CompanyName" VARCHAR(255) );
CREATE TABLE "Downloads" ( "DownloadId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "DownloadEmployeeId" INT REFERENCES "Employees" ("EmployeeId") );
CREATE TABLE "OvertimeApprovalRequests" ( "OvertimeRequestId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "RequestEmployeeId" INT REFERENCES "Employees" ("EmployeeId") );
CREATE TABLE "TimeOffApprovalRequests" ( "TimeOffRequestId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "RequestEmployeeId" INT REFERENCES "Employees" ("EmployeeId") );


-- ============================================================
-- 5. SEEDING DATA
-- ============================================================

INSERT INTO roles (name, display_name) VALUES 
    ('super_admin', 'Super Administrator'), 
    ('employee', 'Employee'); 

INSERT INTO permissions (name, description) VALUES
    ('manage_users', 'Allows full CRUD management over user accounts.'),
    ('manage_roles', 'Allows creating, editing, and deleting user roles and permissions.'),
    ('manage_content', 'Allows creating and editing general site content.'),
    ('view_own_data', 'Allows user to view their own profile/basic data.');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'super_admin';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'employee' AND p.name = 'view_own_data';