-- migrations/0_create_initial_schema.up.sql    
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    display_name VARCHAR(100) NOT NULL
);

CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE "Provinces" (
    "ProvinceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemId" VARCHAR(20) UNIQUE,
    "ProvinceName" VARCHAR(100)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE "TimeZones" (
    "TimeZoneId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TimeZoneName" VARCHAR(100) NOT NULL,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Holidays" (
    "HolidayId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HolidayName" VARCHAR(255),
    "HolidayDate" TIMESTAMPTZ,
    "HolidayDescription" VARCHAR(500),
    "IsNationalHoliday" BOOLEAN,
    "IsCompanyHoliday" BOOLEAN,
    "IsSpecialHoliday" BOOLEAN,
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100),
    "HolidayYear" INT,
    "IsMassLeave" BOOLEAN NOT NULL
);

CREATE TABLE "AttendanceLocations" (
    "AttendanceLocationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TimeZoneId" INT,
    "LocationName" VARCHAR(255),
    "IsFlexible" BOOLEAN,
    "Latitude" NUMERIC(11, 8),
    "Longitude" NUMERIC(11, 8),
    "RadiusToleranceInMeter" INT,
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Company" (
    "CompId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CompName" VARCHAR(150),
    "CompAddress" VARCHAR(500),
    "CompZipCode" VARCHAR(50),
    "CompPhoneNumber" VARCHAR(20),
    "CompMobileNumber" VARCHAR(25),
    "CompEmail" VARCHAR(50),
    "CompWebsite" VARCHAR(300),
    "CompRetirementAge" INT,
    "PersentasePendapatanBPJSTKPemberiKerja" FLOAT,
    "PersentasePendapatanBPJSKSPemberiKerja" FLOAT,
    "PersentasePenguranganBPJSTKPemberiKerja" FLOAT,
    "PersentasePenguranganBPJSKSPemberiKerja" FLOAT,
    "PersentasePenguranganBPJSTKPekerja" FLOAT,
    "PersentasePenguranganBPJSKSPekerja" FLOAT,
    "CompanyPrevMonthDayPayroll" INT NOT NULL DEFAULT 21,
    "CompanyCurrentMonthDayPayroll" INT NOT NULL DEFAULT 20,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(150),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(150)
);

CREATE TABLE "Branches" (
    "BranchId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CompId" INT,
    "TimeZoneId" INT,
    "BranchName" VARCHAR(100) NOT NULL,
    "CompanyName" VARCHAR(255) NOT NULL,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Organizations" (
    "OrganizationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrganizationName" VARCHAR(200) NOT NULL,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "JobLevels" (
    "JobLevelId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobLevelName" VARCHAR(100) NOT NULL,
    "JobLevelOrder" INT,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "JobPositions" (
    "JobPositionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobPositionName" VARCHAR(100),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "EmploymentStatus" (
    "EmploymentStatusId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmploymentStatusName" VARCHAR(100) NOT NULL,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Classes" (
    "ClassId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassCode" VARCHAR(50),
    "Description" VARCHAR(1000),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Grades" (
    "GradeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GradeCode" VARCHAR(50) NOT NULL,
    "GradeDescription" VARCHAR(100) NOT NULL,
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "PtkpTypes" (
    "PtkpTypeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PtkpCode" VARCHAR(20),
    "PtkpName" VARCHAR(100),
    "PtkpAmount" DOUBLE PRECISION,
    "CreatedDate" TIMESTAMP WITHOUT TIME ZONE,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMP WITHOUT TIME ZONE,
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "OvertimeSettings" (
    "OvertimeSettingId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IsRounding" BOOLEAN,
    "OvertimeName" VARCHAR(200),
    "IsDefaultCompensation" BOOLEAN,
    "CompensationDivideNumber" DOUBLE PRECISION,
    "OverrideRupiahPerHour" DOUBLE PRECISION
);

CREATE TABLE "OvertimeMultiplierSettings" (
    "MultiplierSettingId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OvertimeSettingId" INT,
    "FromHour" INT NOT NULL,
    "ToHour" INT NOT NULL,
    "MultipleBy" DOUBLE PRECISION NOT NULL,
    "IsWorkingDay" BOOLEAN
);

CREATE TABLE "ZipCodes" (
    "ZipCodeId" VARCHAR(20) NOT NULL PRIMARY KEY,
    "StreetName" VARCHAR(100),
    "District" VARCHAR(50) NOT NULL,
    "County" VARCHAR(50) NOT NULL,
    "City" VARCHAR(50) NOT NULL,
    "SRProvince" VARCHAR(20),
    "Latitude" DOUBLE PRECISION DEFAULT 0.0,
    "Longitude" DOUBLE PRECISION DEFAULT 0.0,
    "LastUpdateDateTime" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "LastUpdateByUserID" VARCHAR(40),
    "ZipPostalCode" VARCHAR(20) NOT NULL
);

CREATE TABLE "Shifts" (
    "ShiftId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShiftCode" VARCHAR(50),
    "ShiftName" VARCHAR(100),
    "ShiftInHour" VARCHAR(10),
    "ShiftOutHour" VARCHAR(10),
    "BreakStart" VARCHAR(10),
    "BreakEnd" VARCHAR(10),
    "IsShowInRequest" BOOLEAN,
    "IsEnableAttendanceValidation" BOOLEAN,
    "IsEnableDispensation" BOOLEAN,
    "IsWorkShift" BOOLEAN,
    "IsShiftOutHourOverlapDay" BOOLEAN,
    "ClockInMinBefore" INT,
    "ClockOutMaxAfter" INT,
    "ClockInDispensation" INT,
    "ClockOutDispensation" INT,
    "ShiftColorHex" VARCHAR(10),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "TimeOffPolicies" (
    "TimeOffPolicyId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TimeOffPolicyCode" VARCHAR(20) NOT NULL,
    "TimeOffPolicyName" VARCHAR(255) NOT NULL
);

CREATE TABLE "AttendanceTypes" (
    "AttendanceTypeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AttendanceTypeCode" VARCHAR(20),
    "AttendanceTypeName" VARCHAR(50),
    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "StandardReferences" (
    "StandardReferenceId" VARCHAR(100) PRIMARY KEY,
    "StandardReferenceName" VARCHAR(255) NOT NULL,
    "IsActive" BOOLEAN,
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "StandardReferenceItems" (
    "ItemId" VARCHAR(100) PRIMARY KEY,
    "StandardReferenceId" VARCHAR(100),
    "ItemName" VARCHAR(255),
    "IsActive" BOOLEAN,
    "Note" VARCHAR(255),
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "Employees" (
    "EmployeeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BranchId" INT,
    "OrganizationId" INT,
    "JobLevelId" INT,
    "JobPositionId" INT,
    "EmploymentStatusId" INT,
    "ManagerId" INT,
    "ClassId" INT,
    "UserId" BIGINT,                    
    "GradeId" INT,
    "ZipCodeId" VARCHAR(10),
    "PtkpTypeId" INT,
    "OvertimeSettingId" INT,
    "EmployeeAttendanceLocationId" INT,

    "EmployeeNumber" VARCHAR(20) NOT NULL,
    "EmployeeNumberBarcode" VARCHAR(20),
    "FirstName" VARCHAR(50),
    "LastName" VARCHAR(50),
    "Email" VARCHAR(50),
    "JobTitle" VARCHAR(100),
    "IsActive" BOOLEAN,

    "FirstJoinDate" TIMESTAMPTZ,
    "JoinDate" TIMESTAMPTZ,
    "EndDate" TIMESTAMPTZ,
    "SignDate" TIMESTAMPTZ,
    "BirthDate" TIMESTAMPTZ,
    "PassportExpiredDate" TIMESTAMPTZ,

    "WorkPhone" VARCHAR(20),
    "WorkMobile" VARCHAR(25),
    "BirthPlace" VARCHAR(50),
    "CitizenIdAddress" VARCHAR(255),
    "ResidentialAddress" VARCHAR(255),
    "IsSameAddress" BOOLEAN,
    "Tags" VARCHAR(50),
    "Gender" VARCHAR(1),
    "BloodType" VARCHAR(10),
    "MaritalStatusType" VARCHAR(100),
    "ReligionType" VARCHAR(100),
    "Nik" VARCHAR(20),
    "PassportNo" VARCHAR(25),
    "LatestEducationLevelType" VARCHAR(100),
    "IsMedicalStaff" BOOLEAN NOT NULL DEFAULT FALSE,
    "BankAccountType" VARCHAR(100),
    "BankAccountName" VARCHAR(100),
    "BankAccountNumber" VARCHAR(50),
    "BankAccountFilePath" VARCHAR(500),
    "Npwp" VARCHAR(20),
    "BpjsKesehatan" VARCHAR(50),
    "BpjsKesehatanDate" TIMESTAMPTZ,
    "BpjsKetenagakerjaan" VARCHAR(50),
    "BpjsKetenagakerjaanDate" TIMESTAMPTZ,
    "AdditionalBpjsKsDependentsCount" INT NOT NULL DEFAULT 0,

    "GajiPokok" DOUBLE PRECISION,
    "TunjanganKhususYayasan" DOUBLE PRECISION,
    "TunjanganJabatan" DOUBLE PRECISION,
    "UangMakanPerHari" DOUBLE PRECISION,
    "TunjanganPenugasanPenuhWaktu" DOUBLE PRECISION,
    "PotonganBahtera" DOUBLE PRECISION,

    "IsAllowedForOvertime" BOOLEAN,
    "HasRightCutiTahunan" BOOLEAN,
    "EmployeePhotoFilePath" VARCHAR(255),

    "CreatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "UpdatedDate" TIMESTAMPTZ DEFAULT NOW(),
    "CreatedBy" VARCHAR(100),
    "UpdatedBy" VARCHAR(100)
);

CREATE TABLE "AttendanceLogs" (
    "AttendanceLogId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AttendanceTypeId" INT,
    "ShiftId" INT,
    "TimeZoneId" INT,
    "AttendanceLocationId" INT,
    "EmployeeId" INT,
    "AttendanceLogDate" TIMESTAMPTZ,
    "Clock" VARCHAR(10) NOT NULL,
    "Latitude" NUMERIC(11, 8),
    "Longitude" NUMERIC(11, 8),
    "SelfiePath" VARCHAR(255),
    "ClockViaType" VARCHAR(100),
    "InOut" VARCHAR(1),
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100),
    "LateIn" VARCHAR(10),
    "EarlyOut" VARCHAR(10),
    "Note" VARCHAR(1000),
    "ActionDate" TIMESTAMPTZ
);

CREATE TABLE "Attendances" (
    "AttendanceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShiftId" INT,
    "TimeZoneId" INT,
    "AttendanceTypeId" INT,
    "EmployeeId" INT,
    "AttendanceLocationId" INT,
    "AttendanceDate" TIMESTAMPTZ NOT NULL,
    "ClockIn" VARCHAR(10),
    "ClockOut" VARCHAR(10),
    "LateIn" VARCHAR(10),
    "EarlyOut" VARCHAR(10),
    "LatitudeIn" NUMERIC(11, 8),
    "LongitudeIn" NUMERIC(11, 8),
    "LatitudeOut" NUMERIC(11, 8),
    "LongitudeOut" NUMERIC(11, 8),
    "SelfieInPath" VARCHAR(255),
    "SelfieOutPath" VARCHAR(255),
    "ClockInViaType" VARCHAR(100),
    "ClockOutViaType" VARCHAR(100),
    "AttendanceCode" VARCHAR(20),
    "TimeOffPolicyCode" VARCHAR(20),
    "ScheduleWorkingHour" VARCHAR(10),
    "ActualWorkingHour" VARCHAR(10),
    "RealWorkingHour" VARCHAR(10),
    "CreatedDate" TIMESTAMPTZ,
    "CreatedBy" VARCHAR(100),
    "UpdatedDate" TIMESTAMPTZ,
    "UpdatedBy" VARCHAR(100),
    "IsClockOutOverlapDay" BOOLEAN,
    "ClockInNote" VARCHAR(1000),
    "ClockOutNote" VARCHAR(1000),
    "TimeOffPolicyId" INT,
    "ActionDateClockIn" TIMESTAMPTZ,
    "ActionDateClockOut" TIMESTAMPTZ
);

CREATE TABLE "Archives" (
    "ArchiveId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "Category" VARCHAR(50)
);

CREATE TABLE "EmergencyContacts" (
    "EmergencyContactId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "ContactName" VARCHAR(150)
);

CREATE TABLE "FormalEducations" (
    "FormalEducationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "EducationLevelType" VARCHAR(100)
);

CREATE TABLE "InformalEducations" (
    "InformalEducationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "EducationName" VARCHAR(255)
);

CREATE TABLE "Families" (
    "FamilyId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "FamilyName" VARCHAR(150)
);

CREATE TABLE "EmployeeFiles" (
    "EmployeeFileId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "Category" VARCHAR(50)
);

CREATE TABLE "TimeOffs" (
    "TimeOffId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "TimeOffPolicyId" INT,
    "StartDate" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE "WorkExperiences" (
    "WorkExperienceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" INT,
    "CompanyName" VARCHAR(255)
);

CREATE TABLE "Downloads" (
    "DownloadId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DownloadEmployeeId" INT
);

CREATE TABLE "OvertimeApprovalRequests" (
    "OvertimeRequestId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RequestEmployeeId" INT
);

CREATE TABLE "TimeOffApprovalRequests" (
    "TimeOffRequestId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RequestEmployeeId" INT
);

INSERT INTO roles (name, display_name) VALUES
    ('super_admin', 'Super Administrator'),
    ('employee', 'Employee');

INSERT INTO permissions (name, description) VALUES
    ('manage_users', 'Allows full CRUD management over user accounts.'),
    ('manage_roles', 'Allows creating, editing, and deleting user roles and permissions.'),
    ('manage_content', 'Allows creating and editing general site content.'),
    ('view_own_data', 'Allows user to view their own profile/basic data.');

-- Super admin mendapat semua permission
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'super_admin';

-- Employee hanya mendapat view_own_data
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'employee' AND p.name = 'view_own_data';