INSERT INTO "Employees" (
    "FirstName", "LastName", "Email", "EmployeeNumber", "EmployeeNumberBarcode",
    "OrganizationId", "JobPositionId", "JobLevelId", "UserId", "BranchId", "ManagerId",
    "EmploymentStatusId", "Gender", "BirthPlace", "BirthDate", "WorkPhone", "WorkMobile",
    "ZipCodeId", "CitizenIdAddress", "ResidentialAddress", "IsSameAddress",
    "ReligionType", "EmployeeAttendanceLocationId", "OvertimeSettingId",
    "IsAllowedForOvertime", "FirstJoinDate", "JoinDate", "EndDate", "SignDate",
    "BloodType", "MaritalStatusType", "LatestEducationLevelType", "IsMedicalStaff",
    "CreatedDate", "UpdatedDate", "CreatedBy", "UpdatedBy"
)
VALUES 
(
    'Adhitya',
    'Rachman Hidayatullah',
    'adhityarachmanh@gmail.com',
    'RG01',
    'RG01',
    1,
    1,
    1,
    1,
    1,
    NULL,
    1,
    'L',
    'PONTIANAK',
    '1992-07-18',
    '082138921990',
    '082138921990',
    '0000008209',
    'Grand Sharon Residence, Jl. Zingonium Selatan No 30, Mekarjaya, Rancasari, Bandung',
    'Grand Sharon Residence, Jl. Zingonium Selatan No 30, Mekarjaya, Rancasari, Bandung',
    TRUE,
    'Kristen Katolik',
    1,
    1,
    TRUE,
    '2025-09-13',
    '2025-09-13',
    '2027-09-13',
    '2025-09-13',
    'B',
    'Menikah',
    'SKed',
    FALSE,
    NOW(),
    NOW(),
    'System',
    'System'
);